# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'client_start_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_authDialog(object):
    def setupUi(self, authDialog):
        authDialog.setObjectName("authDialog")
        authDialog.resize(220, 100)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("pics/s13f.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        authDialog.setWindowIcon(icon)
        authDialog.setSizeGripEnabled(False)
        authDialog.setModal(False)
        self.buttonBox = QtWidgets.QDialogButtonBox(authDialog)
        self.buttonBox.setGeometry(QtCore.QRect(5, 70, 211, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.nickname = QtWidgets.QLineEdit(authDialog)
        self.nickname.setGeometry(QtCore.QRect(10, 25, 201, 20))
        self.nickname.setInputMask("")
        self.nickname.setObjectName("nickname")
        self.label = QtWidgets.QLabel(authDialog)
        self.label.setGeometry(QtCore.QRect(80, 5, 71, 16))
        self.label.setObjectName("label")
        self.password = QtWidgets.QLineEdit(authDialog)
        self.password.setGeometry(QtCore.QRect(10, 50, 201, 20))
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")

        self.retranslateUi(authDialog)
        self.buttonBox.accepted.connect(authDialog.accept)
        self.buttonBox.rejected.connect(authDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(authDialog)

    def retranslateUi(self, authDialog):
        _translate = QtCore.QCoreApplication.translate
        authDialog.setWindowTitle(_translate("authDialog", "Auth - Messenger by s13f"))
        self.nickname.setPlaceholderText(_translate("authDialog", "nickname"))
        self.label.setText(_translate("authDialog", "Авторизация"))
        self.password.setPlaceholderText(_translate("authDialog", "password"))
