# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'client_contacts_add_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addContactDialog(object):
    def setupUi(self, addContactDialog):
        addContactDialog.setObjectName("addContactDialog")
        addContactDialog.setWindowModality(QtCore.Qt.NonModal)
        addContactDialog.resize(300, 90)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("pics/s13f.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        addContactDialog.setWindowIcon(icon)
        addContactDialog.setModal(True)
        self.buttonBox = QtWidgets.QDialogButtonBox(addContactDialog)
        self.buttonBox.setGeometry(QtCore.QRect(210, 10, 81, 81))
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.refreshButton = QtWidgets.QPushButton(addContactDialog)
        self.refreshButton.setGeometry(QtCore.QRect(10, 60, 181, 23))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("pics/refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.refreshButton.setIcon(icon1)
        self.refreshButton.setObjectName("refreshButton")
        self.label = QtWidgets.QLabel(addContactDialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 201, 16))
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(addContactDialog)
        self.comboBox.setGeometry(QtCore.QRect(10, 30, 181, 22))
        self.comboBox.setObjectName("comboBox")

        self.retranslateUi(addContactDialog)
        self.buttonBox.accepted.connect(addContactDialog.accept)
        self.buttonBox.rejected.connect(addContactDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(addContactDialog)

    def retranslateUi(self, addContactDialog):
        _translate = QtCore.QCoreApplication.translate
        addContactDialog.setWindowTitle(_translate("addContactDialog", "Add contact - Messenger by s13f"))
        self.refreshButton.setText(_translate("addContactDialog", "Refresh list"))
        self.label.setText(_translate("addContactDialog", "Выберите контакт для добавления:"))
