# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'client_contacts_del_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_deleteContactDialog(object):
    def setupUi(self, deleteContactDialog):
        deleteContactDialog.setObjectName("deleteContactDialog")
        deleteContactDialog.resize(300, 90)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("pics/s13f.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        deleteContactDialog.setWindowIcon(icon)
        deleteContactDialog.setModal(True)
        self.buttonBox = QtWidgets.QDialogButtonBox(deleteContactDialog)
        self.buttonBox.setGeometry(QtCore.QRect(210, 10, 81, 81))
        self.buttonBox.setAutoFillBackground(False)
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(deleteContactDialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 201, 16))
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(deleteContactDialog)
        self.comboBox.setGeometry(QtCore.QRect(10, 30, 181, 22))
        self.comboBox.setObjectName("comboBox")

        self.retranslateUi(deleteContactDialog)
        self.buttonBox.accepted.connect(deleteContactDialog.accept)
        self.buttonBox.rejected.connect(deleteContactDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(deleteContactDialog)

    def retranslateUi(self, deleteContactDialog):
        _translate = QtCore.QCoreApplication.translate
        deleteContactDialog.setWindowTitle(_translate("deleteContactDialog", "Delete contact - Messenger by s13f"))
        self.label.setText(_translate("deleteContactDialog", "Выберите контакт для удаления:"))
